# Generated by Django 3.0 on 2020-06-16 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemembership',
            name='invitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Space'),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='invitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_invitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Room'),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='space',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.Space'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='space.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='spacemembership',
            unique_together={('space', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('room', 'user')},
        ),
    ]
