# Generated by Django 3.0 on 2020-06-25 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0003_room_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='roomMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
