# Generated by Django 3.0 on 2020-06-30 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0004_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Space'),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='invitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomInvitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited'), ('DECLINED', 'Decline')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='membership_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=8),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomMemberships', to='space.Room'),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='invitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaceInvitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited'), ('DECLINED', 'Decline')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='membership_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=8),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaceMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('space', 'display_name')},
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_deleted',
        ),
    ]
