# Generated by Django 3.0 on 2020-06-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_room_s_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='s_deleted',
            new_name='is_deleted',
        ),
    ]
