# Generated by Django 3.0 on 2020-06-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_auto_20200630_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.Space'),
        ),
    ]
