# Generated by Django 3.0 on 2020-06-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_auto_20200630_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('space', 'room_id')},
        ),
    ]
