# Generated by Django 3.0 on 2020-07-02 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0014_auto_20200701_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='spaceMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
