version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
      image: docker.elastic.co/kibana/kibana:7.13.2
      container_name: kibana
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      networks:
        - elastic

volumes: 
  elastic-data-volume:
    driver: local

networks:
  elastic:
    driver: bridge