# Generated by Django 3.0 on 2021-06-22 22:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('court_name', models.CharField(max_length=200)),
                ('case_name', models.CharField(max_length=200)),
                ('case_number', models.CharField(max_length=100)),
                ('case_class', models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal')], max_length=10)),
                ('case_action', models.CharField(choices=[('Revision', 'Revision'), ('Judgment', 'Judgment')], max_length=10)),
                ('citation', models.CharField(max_length=200)),
                ('parties', models.CharField(blank=True, max_length=200, null=True)),
                ('file_id', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('judges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('person_type', models.CharField(choices=[('JUDGE', 'Judge')], max_length=20)),
            ],
        ),
    ]
