apiVersion: v1
kind: Service
metadata:
  name: skyspace-api
  labels:
    app: skyspace-api
spec:
    type: NodePort
    ports:
    -   port: 8000
        targetPort: 8000
        protocol: TCP
        name: http
        nodePort: 30002
    selector:
        app: skyspace-api
